//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.31 at 10:39:46 PM BRST 
//


package br.com.fiap.mba.scj.gerenciamento_filas;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the br.com.fiap.mba.scj.gerenciamento_filas package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: br.com.fiap.mba.scj.gerenciamento_filas
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link IniciarAtendimentoRequest }
     * 
     */
    public IniciarAtendimentoRequest createIniciarAtendimentoRequest() {
        return new IniciarAtendimentoRequest();
    }

    /**
     * Create an instance of {@link FinalizarAtendimentoRequest }
     * 
     */
    public FinalizarAtendimentoRequest createFinalizarAtendimentoRequest() {
        return new FinalizarAtendimentoRequest();
    }

    /**
     * Create an instance of {@link FinalizarAtendimentoResponse }
     * 
     */
    public FinalizarAtendimentoResponse createFinalizarAtendimentoResponse() {
        return new FinalizarAtendimentoResponse();
    }

    /**
     * Create an instance of {@link ProximaSenhaResponse }
     * 
     */
    public ProximaSenhaResponse createProximaSenhaResponse() {
        return new ProximaSenhaResponse();
    }

    /**
     * Create an instance of {@link ProximaSenhaRequest }
     * 
     */
    public ProximaSenhaRequest createProximaSenhaRequest() {
        return new ProximaSenhaRequest();
    }

    /**
     * Create an instance of {@link IniciarAtendimentoResponse }
     * 
     */
    public IniciarAtendimentoResponse createIniciarAtendimentoResponse() {
        return new IniciarAtendimentoResponse();
    }

    /**
     * Create an instance of {@link GerarSenhaRequest }
     * 
     */
    public GerarSenhaRequest createGerarSenhaRequest() {
        return new GerarSenhaRequest();
    }

    /**
     * Create an instance of {@link GerarSenhaResponse }
     * 
     */
    public GerarSenhaResponse createGerarSenhaResponse() {
        return new GerarSenhaResponse();
    }

}
