//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.31 at 10:39:46 PM BRST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.fiap.com.br/mba/scj/gerenciamento_filas", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package br.com.fiap.mba.scj.gerenciamento_filas;
